Repository Goldfish7718/Dev.hike, pull requests merged in 2024-04, with the labels that each got.

#29 build[User]: Add User Profile page;
  client/src/main.tsx
  client/src/views/User1.tsx
Labels: feature

#32 feat & release[Second release]: Integrate second features of contributors to master;
  client/src/data/eventData.json
  client/src/data/postData.json
  client/src/main.tsx
  client/src/views/Dashboard.tsx
  client/src/views/NewPost.tsx
  client/src/views/User1.tsx
Labels: enhancement, feature

#22 chore[NewPost]: Add Tag User input;
  client/src/views/NewPost.tsx
Labels: enhancement

#26 build[Posts]: Add Tagged People and reply button;
  client/src/data/postData.json
  client/src/views/Dashboard.tsx
Labels: enhancement

#30 build[InitiateProfileFirst]: Add Initiate Profile First page;
  client/src/components/ui/badge.tsx
  client/src/main.tsx
  client/src/views/InitiateProfileFirst.tsx
Labels: feature

#28 build[ReplyDialog]: Add Reply Dialog;
  client/package-lock.json
  client/package.json
  client/src/components/ReplyDialogTrigger.tsx
  client/src/components/ui/scroll-area.tsx
  client/src/data/replyData.json
  client/src/layouts/dashboard-layout.tsx.tsx
Labels: feature

#33 build[Search Dialog]: Add Search Dialog;
  client/src/layouts/dashboard-layout.tsx.tsx
Labels: enhancement

#27 build[InitiateProfileSecond]: Add Initiate Profile Second page;
  client/src/main.tsx
  client/src/views/InitiateProfileSecond.tsx
Labels: feature

#34 fix[Third release]: Add bug fixes and enhancements for 3rd feature integrations;
  client/src/components/EventCard.tsx
  client/src/components/EventRegister.tsx
  client/src/components/Navbar.tsx
  client/src/components/PostCard.tsx
  client/src/components/SearchDialogTrigger.tsx
  client/src/components/TimelineCard.tsx
  client/src/data/postData.json
  client/src/layouts/dashboard-layout.tsx.tsx
  client/src/main.tsx
  client/src/types/types1.ts
  client/src/views/Dashboard.tsx
  client/src/views/InitiateProfileFirst.tsx
  client/src/views/InitiateProfileSecond.tsx
  client/src/views/Profile.tsx
  client/src/views/User.tsx
Labels: enhancement

#35 feat & release[Third features]: Add 3rd feature integrations to masster;
  client/package-lock.json
  client/package.json
  client/src/components/EventCard.tsx
  client/src/components/EventRegister.tsx
  client/src/components/Navbar.tsx
  client/src/components/PostCard.tsx
  client/src/components/ReplyDialogTrigger.tsx
  client/src/components/SearchDialogTrigger.tsx
  client/src/components/TimelineCard.tsx
  client/src/components/ui/badge.tsx
  client/src/components/ui/scroll-area.tsx
  client/src/data/postData.json
  client/src/data/replyData.json
  client/src/layouts/dashboard-layout.tsx.tsx
  client/src/main.tsx
  client/src/types/types1.ts
  client/src/views/Dashboard.tsx
  client/src/views/InitiateProfileFirst.tsx
  client/src/views/InitiateProfileSecond.tsx
  client/src/views/NewPost.tsx
  client/src/views/Profile.tsx
  client/src/views/User.tsx
Labels: enhancement, feature

#38 feat[Profile Model]: Add Profile model and related CRUD ops;
  client/package-lock.json
  client/package.json
  client/src/components/ui/toast.tsx
  client/src/components/ui/toaster.tsx
  client/src/components/ui/use-toast.ts
  client/src/context/UserContext.tsx
  client/src/layouts/root-layout.tsx
  client/src/main.tsx
  client/src/views/InitiateProfileFirst.tsx
  client/src/views/InitiateProfileSecond.tsx
  client/src/views/Profile.tsx
  server/controllers/index.js
  server/controllers/profileControllers.js
  server/index.js
  server/models/index.js
  server/models/profileSchema.js
  server/package-lock.json
  server/package.json
  server/routes/index.js
  server/routes/profileRoutes.js
  server/utils/index.js
Labels: feature

#43 feat[Backend/Post]: Add Posts Controllers;
  server/controllers/postControllers.js
  server/models/postSchema.js
  server/routes/postRoutes.js
Labels: feature

#45 feat[Backend/Replies]: Add Reply Model and related CRD ops.
  server/controllers/postControllers.js
  server/controllers/replyControllers.js
  server/models/replySchema.js
  server/routes/postRoutes.js
  server/routes/replyRoutes.js
Labels: feature

#44 feat[Backend/Events]: Add Event controllers;
  server/controllers/eventControllers.js
  server/models/eventSchema.js
  server/routes/eventRoutes.js
Labels: feature

#47 feat[Backend]: Add Server-side logic with all 5 models.
  client/package-lock.json
  client/package.json
  client/src/components/ui/toast.tsx
  client/src/components/ui/toaster.tsx
  client/src/components/ui/use-toast.ts
  client/src/context/UserContext.tsx
  client/src/layouts/root-layout.tsx
  client/src/main.tsx
  client/src/views/InitiateProfileFirst.tsx
  client/src/views/InitiateProfileSecond.tsx
  client/src/views/Profile.tsx
  server/.gitignore
  server/controllers/eventControllers.js
  server/controllers/postControllers.js
  server/controllers/profileControllers.js
  server/controllers/replyControllers.js
  server/controllers/timelineControllers.js
  server/index.js
  server/models/eventSchema.js
  server/models/postSchema.js
  server/models/profileSchema.js
  server/models/replySchema.js
  server/models/timelineSchema.js
  server/package-lock.json
  server/package.json
  server/routes/eventRoutes.js
  server/routes/postRoutes.js
  server/routes/profileRoutes.js
  server/routes/replyRoutes.js
  server/routes/timelineRoutes.js
Labels: feature

#48 feat[Backend]: Add server-side logic [STABLE]
  client/package-lock.json
  client/package.json
  client/src/components/ui/toast.tsx
  client/src/components/ui/toaster.tsx
  client/src/components/ui/use-toast.ts
  client/src/context/UserContext.tsx
  client/src/layouts/root-layout.tsx
  client/src/main.tsx
  client/src/views/InitiateProfileFirst.tsx
  client/src/views/InitiateProfileSecond.tsx
  client/src/views/Profile.tsx
  server/.gitignore
  server/controllers/eventControllers.js
  server/controllers/postControllers.js
  server/controllers/profileControllers.js
  server/controllers/replyControllers.js
  server/controllers/timelineControllers.js
  server/index.js
  server/models/eventSchema.js
  server/models/postSchema.js
  server/models/profileSchema.js
  server/models/replySchema.js
  server/models/timelineSchema.js
  server/package-lock.json
  server/package.json
  server/routes/eventRoutes.js
  server/routes/postRoutes.js
  server/routes/profileRoutes.js
  server/routes/replyRoutes.js
  server/routes/timelineRoutes.js
Labels: enhancement, feature

#49 feat[Integration]: Integrate Backend endpoints to client side
  client/src/components/EditProfileTriggers.tsx
  client/src/components/EventCard.tsx
  client/src/components/EventRegister.tsx
  client/src/components/PostCard.tsx
  client/src/components/ReplyDialogTrigger.tsx
  client/src/components/TimelineCard.tsx
  client/src/context/UserContext.tsx
  client/src/data/postData.json
  client/src/main.tsx
  client/src/types/types1.ts
  client/src/views/Dashboard.tsx
  client/src/views/NewEvent.tsx
  client/src/views/NewPost.tsx
  client/src/views/NewTimeLine.tsx
  client/src/views/Profile.tsx
  client/src/views/User.tsx
  server/controllers/eventControllers.js
  server/controllers/postControllers.js
  server/controllers/profileControllers.js
  server/controllers/replyControllers.js
  server/controllers/timelineControllers.js
  server/models/eventSchema.js
  server/models/postSchema.js
  server/models/profileSchema.js
  server/routes/eventRoutes.js
  server/routes/postRoutes.js
  server/routes/profileRoutes.js
  server/utils/convertDate.js
Labels: enhancement, feature

#50 feat[Integration]: Integrate Backend Endpoints;
  client/src/components/EditProfileTriggers.tsx
  client/src/components/EventCard.tsx
  client/src/components/EventRegister.tsx
  client/src/components/PostCard.tsx
  client/src/components/ReplyDialogTrigger.tsx
  client/src/components/TimelineCard.tsx
  client/src/context/UserContext.tsx
  client/src/data/postData.json
  client/src/main.tsx
  client/src/types/types1.ts
  client/src/views/Dashboard.tsx
  client/src/views/NewEvent.tsx
  client/src/views/NewPost.tsx
  client/src/views/NewTimeLine.tsx
  client/src/views/Profile.tsx
  client/src/views/User.tsx
  server/controllers/eventControllers.js
  server/controllers/postControllers.js
  server/controllers/profileControllers.js
  server/controllers/replyControllers.js
  server/controllers/timelineControllers.js
  server/models/eventSchema.js
  server/models/postSchema.js
  server/models/profileSchema.js
  server/routes/eventRoutes.js
  server/routes/postRoutes.js
  server/routes/profileRoutes.js
  server/utils/convertDate.js
Labels: enhancement, feature
